/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.minesweeper;

import javax.swing.border.*;

/**
 *
 * @author victor
 */
public class UpperPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpperPanel
     */
    public UpperPanel() {
        initComponents();
        myInit();
    }
    
    private void myInit() {
        buttonSmile.setFocusable(false);
        Border border = labelTime.getBorder();
        Border margin = new EmptyBorder(10,5,5,5);
        labelTime.setBorder(new CompoundBorder(border, margin)); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelLeft = new javax.swing.JPanel();
        panelRight = new javax.swing.JPanel();
        labelTime = new javax.swing.JLabel();
        panelCenter = new javax.swing.JPanel();
        buttonSmile = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new java.awt.BorderLayout());

        panelLeft.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout panelLeftLayout = new javax.swing.GroupLayout(panelLeft);
        panelLeft.setLayout(panelLeftLayout);
        panelLeftLayout.setHorizontalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLeftLayout.setVerticalGroup(
            panelLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        add(panelLeft, java.awt.BorderLayout.LINE_START);

        panelRight.setBackground(new java.awt.Color(204, 255, 255));
        panelRight.setLayout(new java.awt.GridBagLayout());

        labelTime.setBackground(new java.awt.Color(0, 0, 0));
        labelTime.setFont(new java.awt.Font("Keraleeyam", 1, 24)); // NOI18N
        labelTime.setForeground(new java.awt.Color(255, 51, 51));
        labelTime.setText("0:00");
        labelTime.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 23, 31, 31);
        panelRight.add(labelTime, gridBagConstraints);

        add(panelRight, java.awt.BorderLayout.LINE_END);

        panelCenter.setBackground(new java.awt.Color(255, 255, 204));
        panelCenter.setLayout(new java.awt.GridBagLayout());

        buttonSmile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/smiley.png"))); // NOI18N
        buttonSmile.setAlignmentX(0.5F);
        buttonSmile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonSmile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSmileActionPerformed(evt);
            }
        });
        panelCenter.add(buttonSmile, new java.awt.GridBagConstraints());

        add(panelCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSmileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSmileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSmileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSmile;
    private javax.swing.JLabel labelTime;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRight;
    // End of variables declaration//GEN-END:variables

   
}
